### ISSUE TITLE
函数内部函数怎么用啊？

### ISSUE THREAD

**Issue by Maneng** [zebra110/SUMMER-FLAG#1]
```javascript

  function f1(){
        var n=999;
        nAdd=function(){n+=1}
        function f2(){
          alert(n);
        }
        return f2;
      }
      var result=f1();
      result(); // 999
      nAdd();
      result(); // 1000
```

为什么可以直接用nAdd() 函数啊？

**Comment by zebra110** [comment]
nAdd=function(){n+=1}和function nAdd(){n+=1}是不一样的 前者是把函数赋值给nAdd 相当于f1的一个属性 就可以访问，而后者是内部函数，确实不可以访问。好问题，我一开始也纠结了一会~臭屁能哥==我好想你啊呜呜呜

**Comment by Maneng** [comment]
函数内部的属性可以直接访问吗？
还有你的代码片段 修改下 用` ```  ``` `包起来

**Comment by Maneng** [comment]
@zebra110  hello 回复我试试看

**Comment by zebra110** [comment]
是的，属性是可以访问的，因为你已经执行过f1了，因为闭包，所以f1函数作用域中的属性和函数没有被销毁，所以可以被访问啦。
我在网上找用了4个tab键~~我说怎么还是怪怪的，学习啦。

**Comment by Maneng** [comment]
# _测试语法呀_

##  嘿嘿

- 😁

1. 😏

- [ ] 😃

- [x] 😭 

## 代码块
`var a = 10`

## 引用
> 你好呀

**Comment by Maneng** [comment]
💖

**Comment by Maneng** [comment]
大概懂了👍

**Comment by zebra110** [comment]
🙃

**Comment by zebra110** [comment]
🐴❤🐷

**Comment by zebra110** [comment]
🐷❤🐴

**Comment by Maneng** [comment]
@zebra110  嘻嘻 么么哒🌹

**Comment by Maneng** [comment]
拉拉
